import pm2 from "pm2";
import { ActionResponse } from "../interfaces/IResponses";
import { SpinalGraph, SpinalNode } from "spinal-model-graph";
declare class Pm2Service {
    private static _instance;
    private _isConnected;
    pm2Maps: Map<string | number, SpinalNode>;
    private _context;
    private intervalHandle;
    private _logSyncked;
    private constructor();
    static getInstance(): Pm2Service;
    initialize(graph: SpinalGraph): Promise<void>;
    listentPm2Actions(callback: (data: any) => void): Promise<void>;
    updatePm2Processes(): Promise<void>;
    startPeriodicPm2MetricsPush(interval?: number | string): Promise<void>;
    removePm2ProcessFromGraph(processNode: SpinalNode): Promise<void>;
    updatePm2ProcessesMetrics(processNode: SpinalNode, pm2Process: pm2.ProcessDescription): void;
    addPm2ProcessToGraph(pm2Process: pm2.ProcessDescription): Promise<SpinalNode | null>;
    private _buildPm2ProcessNodeInfo;
    private _addLogRelationToPm2Process;
    private _createOrGetPm2Context;
    private _initializePm2Processes;
    private _watchAndSyncLogs;
    private _syncLogForProcess;
    getAllPm2Processes(): Promise<pm2.ProcessDescription[]>;
    getPm2ProcessByKey(key: string): Promise<pm2.ProcessDescription | null>;
    startPm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    stopPm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    restartPm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    private listenPm2Events;
    getPm2MetricsFormatted(): Promise<{
        name: string | undefined;
        pm_id: number | undefined;
        status: string | undefined;
        cpu: number | undefined;
        memory: number | undefined;
        uptime: number | undefined;
    }[]>;
    private _connectToPm2;
    private _listPm2Processes;
    private _disconnectFromPm2;
}
export { Pm2Service };
export default Pm2Service;
