import pm2 from "pm2";
import { ActionResponse, Pm2LogType, Pm2ProcessLogsResponse, Pm2ProcessMetricsResponse, Pm2StatusSummaryResponse } from "../interfaces/IResponses";
import { SpinalNode } from "spinal-model-graph";
import { IPm2EventData } from "../interfaces";
export type Pm2LogPayload = {
    pm_id: number;
    name: string;
    type: Pm2LogType;
    file: string;
    content: string;
};
export type Pm2LogCallback = (data: Pm2LogPayload) => void;
declare class Pm2Service {
    private static _instance;
    private _isConnected;
    pm2Maps: Map<string | number, SpinalNode>;
    private logsWatcher;
    private _pm2LogWatchCallback?;
    private _pm2LogWatchSyncTimer?;
    private _isPm2LogBusSubscribed;
    private constructor();
    static getInstance(): Pm2Service;
    listenToPm2Actions(callback: (data: IPm2EventData) => void): Promise<void>;
    watchPm2Logs(callback: Pm2LogCallback): Promise<void>;
    stopWatchingPm2Logs(): void;
    private _subscribeToPm2LogLifecycleEvents;
    private _schedulePm2LogWatchersSync;
    private _syncPm2LogWatchers;
    private _getProcessLogTargets;
    private _shouldWatchProcessLogs;
    private _createLogWatcher;
    private _emitInitialLogContent;
    private _emitAppendedLogContent;
    private _readLogSlice;
    getAllPm2Processes(): Promise<pm2.ProcessDescription[]>;
    getPm2ProcessByKey(key: string): Promise<pm2.ProcessDescription | null>;
    startPm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    stopPm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    restartPm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    reloadPm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    deletePm2Process(processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    runPm2Action(action: "start" | "stop" | "restart" | "reload" | "delete", processKeys: string | number | (string | number)[]): Promise<ActionResponse[]>;
    getPm2StatusSummary(): Promise<Pm2StatusSummaryResponse>;
    getPm2ProcessMetricsByKey(key: string): Promise<Pm2ProcessMetricsResponse | null>;
    getPm2ProcessLogsByKey(key: string, tail?: number, logType?: Pm2LogType): Promise<Pm2ProcessLogsResponse | null>;
    private _executePm2BulkAction;
    private _readLogTail;
    private subscribeToPm2EventStream;
    getPm2MetricsFormatted(): Promise<{
        name: string | undefined;
        pm_id: number | undefined;
        status: string | undefined;
        cpu: number | undefined;
        memory: number | undefined;
        uptime: number | undefined;
    }[]>;
    private _connectToPm2;
    private _listPm2Processes;
    private _disconnectFromPm2;
    private _savePm2Event;
}
export { Pm2Service };
export default Pm2Service;
